### ISSUE TITLE
Save DCs don't appear correctly for cantrips

### ISSUE THREAD

**Issue by cs96and** [slcao2/FoundryVTT-QuickRolls#20] opened 2020-12-02 00:25 UTC
If you cast a cantrip with a save DC, the button in the chat box just says "Saving throw".  If you change the spell to be a levelled spell, then it appears correctly (e.g. "Saving Throw DC 14 Strength")

**Comment by slcao2** [comment] 2020-12-02 01:33
Ah more spells. I really need to check those. I'll take a look.

**Comment by slcao2** [comment] 2020-12-02 01:46
@cs96and Can you show me a screenshot of it? I am not able to reproduce it on my client.

**Comment by cs96and** [comment] 2020-12-02 22:22
This appears to be fixed with the latest version.

**Comment by cs96and** [comment] 2020-12-02 22:39
Sorry I realized I still had better rolls enabled when I tested it just now!  I discovered that the problem only presents itself when the spell has a measured template as well.  E.g. here's the default Acid Splash (everything looks OK)...

![image](https://user-images.githubusercontent.com/898086/100939882-f576da80-34ee-11eb-8948-aa56409f68b4.png)

Now if I change the spell to target a 10 ft cube...

![image](https://user-images.githubusercontent.com/898086/100939958-12aba900-34ef-11eb-9f02-8c2bbcfe343b.png)

Now if I keep the 10ft cube, cut change it to be a 1st level spell, it works again...

![image](https://user-images.githubusercontent.com/898086/100940082-3c64d000-34ef-11eb-9608-c376cf83d750.png)

**Comment by slcao2** [comment] 2020-12-02 22:58
Hmm looks like this is happening with the vanilla roll dnd5e roll system as well. Seems like it might be an issue with the system like the other bug.

**Comment by slcao2** [comment] 2020-12-03 01:40
Linked to https://gitlab.com/foundrynet/dnd5e/-/issues/820. Thanks for adding to the issue!

**Comment by cs96and** [comment] 2020-12-14 18:18
This seems to be fixed in the dnd5e 1.2.0 module.

**Comment by slcao2** [comment] 2020-12-14 18:29
@cs96and Awesome. Closing.

**Closed as completed by slcao2** 2020-12-14 18:29 UTC
Labels: bug
